type_tag: "Type"    # how the Type of an entity, df, class, etc. is called

entity_type_mode: 'property'

# Neo4j configuration
neo4j:
  URI: 'bolt://localhost:7687'
  username: "neo4j"
  password: "12341234"
